// Florida Masonic Lodges — Official Grand Lodge source
// 257 lodges · lodges.glflamason.org · May 2026
export const floridaLodges = [
  { name: 'Jackson Lodge', number: '1', city: 'TALLAHASSEE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 181 },
  { name: 'Washington Lodge', number: '2', city: 'Quincy', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 45 },
  { name: 'Harmony Lodge', number: '3', city: 'MARIANNA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 61 },
  { name: 'Joppa Lodge', number: '4', city: 'OLD TOWN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 27 },
  { name: 'Hiram Lodge', number: '5', city: 'MONTICELLO', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 51 },
  { name: 'Tuscan Lodge', number: '6', city: 'BARTOW', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 40 },
  { name: 'Pine Hill Lodge', number: '9', city: 'BROOKER', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 23 },
  { name: 'Waldo Lodge', number: '10', city: 'WALDO', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 25 },
  { name: 'Madison Lodge', number: '11', city: 'MADISON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 131 },
  { name: 'Cherry Hill Lodge', number: '12', city: 'FORT WHITE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 48 },
  { name: 'Wellborn Lodge', number: '13', city: 'WELLBORN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 67 },
  { name: 'Escambia Lodge', number: '15', city: 'PENSACOLA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 264 },
  { name: 'Santa Rosa Lodge', number: '16', city: 'MILTON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 62 },
  { name: 'Wauchula Lodge', number: '17', city: 'WAUCHULA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 60 },
  { name: 'Marion-Dunn Lodge', number: '19', city: 'OCALA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 162 },
  { name: 'Solomon Lodge', number: '20', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 174 },
  { name: 'Gee Lodge', number: '21', city: 'CHATTAHOOCHEE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 24 },
  { name: 'Temple Lodge', number: '23', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 85 },
  { name: 'Naval Lodge', number: '24', city: 'PENSACOLA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 143 },
  { name: 'Hillsborough Lodge', number: '25', city: 'TAMPA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 375 },
  { name: 'Lake City Lodge', number: '27', city: 'LAKE CITY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 87 },
  { name: 'Greenville Lodge', number: '28', city: 'GREENVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 34 },
  { name: 'Micanopy Lodge', number: '29', city: 'Micanopy', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 82 },
  { name: 'Bushnell-Hernando Lodge', number: '30', city: 'BUSHNELL', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 75 },
  { name: 'Manatee Lodge', number: '31', city: 'BRADENTON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 154 },
  { name: 'Callahan Lodge', number: '32', city: 'CALLAHAN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 150 },
  { name: 'Palatka Lodge', number: '34', city: 'PALATKA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 69 },
  { name: 'Bradford Lodge', number: '35', city: 'STARKE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 70 },
  { name: 'Orange Lodge', number: '36', city: 'APOPKA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 127 },
  { name: 'Saint Johns Lodge', number: '37', city: 'DELAND', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 106 },
  { name: 'Wausau Lodge', number: '39', city: 'WAUSAU', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 56 },
  { name: 'Orion Lodge', number: '40', city: 'CHIPLEY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 37 },
  { name: 'Gainesville Lodge', number: '41', city: 'GAINESVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 127 },
  { name: 'Pensacola Lodge', number: '42', city: 'PENSACOLA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 154 },
  { name: 'Barrett Lodge', number: '43', city: 'LIVE OAK', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 68 },
  { name: 'Laurel Hill Lodge', number: '44', city: 'LAUREL HILL', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 26 },
  { name: 'Amelia Lodge', number: '47', city: 'FERNANDINA BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 165 },
  { name: 'Dade City Lodge', number: '48', city: 'Dade City', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 42 },
  { name: 'Marston Lodge', number: '49', city: 'FORT MCCOY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 89 },
  { name: 'Concord Lodge', number: '50', city: 'CRESTVIEW', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 88 },
  { name: 'Brown Lodge', number: '51', city: 'CHIEFLAND', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 63 },
  { name: 'Lake Butler Lodge', number: '52', city: 'LAKE BUTLER', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 40 },
  { name: 'Friendship Lodge', number: '53', city: 'OCALA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 126 },
  { name: 'Tropical Lodge', number: '56', city: 'FORT MYERS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 226 },
  { name: 'Leesburg Lodge', number: '58', city: 'LEESBURG', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 98 },
  { name: 'Dawkins Lodge', number: '60', city: 'SANDERSON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 41 },
  { name: 'Moore Haven Lodge', number: '61', city: 'MOORE HAVEN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 50 },
  { name: 'Sanford Lodge', number: '62', city: 'SANFORD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 100 },
  { name: 'Key West Lodge', number: '64', city: 'KEY WEST', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 221 },
  { name: 'Umatilla Lodge', number: '65', city: 'UMATILLA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 62 },
  { name: 'Peace River Lodge', number: '66', city: 'ARCADIA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 45 },
  { name: 'Orlando Lodge', number: '69', city: 'ORLANDO', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 149 },
  { name: 'John M. Caldwell Lodge', number: '70', city: 'JASPER', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 20 },
  { name: 'Lake Lodge', number: '72', city: 'LAKE COMO', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 53 },
  { name: 'Curfew Lodge', number: '73', city: 'CARRABELLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 53 },
  { name: 'Apalachicola Lodge', number: '76', city: 'APALACHICOLA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 48 },
  { name: 'Volusia Lodge', number: '77', city: 'Pierson', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 66 },
  { name: 'Star Lodge', number: '78', city: 'Largo', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 89 },
  { name: 'Olin S. Wright Lodge', number: '79', city: 'PLANT CITY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 83 },
  { name: 'Orange Blossom Lodge', number: '80', city: 'KISSIMMEE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 142 },
  { name: 'Raiford Lodge', number: '82', city: 'RAIFORD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 51 },
  { name: 'Peninsular Lodge', number: '85', city: 'TAVARES', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 84 },
  { name: 'Pineland Lodge', number: '86', city: 'PALATKA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 110 },
  { name: 'Fort Pierce Lodge', number: '87', city: 'Fort Pierce', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 156 },
  { name: 'Melrose Lodge', number: '89', city: 'KEYSTONE HEIGHTS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 74 },
  { name: 'Indian River Lodge', number: '90', city: 'TITUSVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 203 },
  { name: 'Lakeland Lodge', number: '91', city: 'LAKELAND', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 206 },
  { name: 'Wildwood Lodge', number: '92', city: 'WILDWOOD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 71 },
  { name: 'Corinth Lodge', number: '93', city: 'WELLBORN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 26 },
  { name: 'Morning Star Lodge', number: '94', city: 'SILVER SPRINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 60 },
  { name: 'Belleview Lodge', number: '95', city: 'BELLEVIEW', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 66 },
  { name: 'Red Rock Lodge', number: '96', city: 'Milton', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 19 },
  { name: 'Ashlar Lodge', number: '98', city: 'HASTINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 243 },
  { name: 'Royal Palm Lodge', number: '100', city: 'HOMESTEAD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 94 },
  { name: 'Ionic Lodge', number: '101', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 93 },
  { name: 'Hawthorne Lodge', number: '103', city: 'HAWTHORNE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 29 },
  { name: 'De Soto Lodge', number: '105', city: 'Riverview', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 202 },
  { name: 'Middleburg Lodge', number: '107', city: 'MIDDLEBURG', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 133 },
  { name: 'Herman Lodge', number: '108', city: 'FREEPORT', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 43 },
  { name: 'Dixie Lodge', number: '109', city: 'BLOUNTSTOWN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 47 },
  { name: 'Tarpon Lodge', number: '112', city: 'TARPON SPRINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 93 },
  { name: 'Brevard Lodge', number: '113', city: 'COCOA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 112 },
  { name: 'Brandon Lodge', number: '114', city: 'BRANDON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 329 },
  { name: 'Punta Gorda Lodge', number: '115', city: 'PUNTA GORDA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 120 },
  { name: 'Cabul Lodge', number: '116', city: 'GREEN COVE SPRINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 97 },
  { name: 'Ornan Lodge', number: '117', city: 'WILLISTON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 35 },
  { name: 'Mayo Lodge', number: '119', city: 'MAYO', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 25 },
  { name: 'Perry Lodge', number: '123', city: 'PERRY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 80 },
  { name: 'Biscayne Bay Lodge', number: '124', city: 'MIAMI', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 122 },
  { name: 'Albert J. Russell Lodge', number: '126', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 191 },
  { name: 'Clearwater Lodge', number: '127', city: 'Clearwater', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 171 },
  { name: 'Branford Lodge', number: '130', city: 'BRANFORD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 25 },
  { name: 'Mount Ewell Lodge', number: '131', city: 'BAKER', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 39 },
  { name: 'Red Level Lodge', number: '134', city: 'MARIANNA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 34 },
  { name: 'High Springs Lodge', number: '137', city: 'HIGH SPRINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 73 },
  { name: 'Harmonia Lodge', number: '138', city: 'West Palm Beach', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 184 },
  { name: 'St. Petersburg Lodge', number: '139', city: 'SAINT PETERSBURG', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 231 },
  { name: 'Doric Lodge', number: '140', city: 'FORT LAUDERDALE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 486 },
  { name: 'Trilby Lodge', number: '141', city: 'Dade City', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 59 },
  { name: 'Parker Lodge', number: '142', city: 'PARKER', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 91 },
  { name: 'Melbourne Lodge', number: '143', city: 'WEST MELBOURNE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 180 },
  { name: 'Oleeta-West Dade Lodge', number: '145', city: 'MIAMI SPRINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 129 },
  { name: 'Pearl of the West Lodge', number: '146', city: 'NEW PORT RICHEY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 173 },
  { name: 'Sarasota Lodge', number: '147', city: 'SARASOTA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 270 },
  { name: 'New Smyrna Lodge', number: '149', city: 'EDGEWATER', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 287 },
  { name: 'PTF United Lodge', number: '153', city: 'TAMPA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 155 },
  { name: 'Ponce de Leon Lodge', number: '157', city: 'WESTVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 38 },
  { name: 'Duval Lodge', number: '159', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 102 },
  { name: 'Fort Meade Lodge', number: '160', city: 'FORT MEADE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 43 },
  { name: 'Acacia Lodge', number: '163', city: 'STUART', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 287 },
  { name: 'Vernon Lodge', number: '164', city: 'VERNON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 15 },
  { name: 'Winter Garden Lodge', number: '165', city: 'WINTER GARDEN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 168 },
  { name: 'Havana Lodge', number: '167', city: 'Havana', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 24 },
  { name: 'DeFuniak Lodge', number: '170', city: 'DEFUNIAK SPRINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 61 },
  { name: 'Boca-Delray Lodge', number: '171', city: 'BOCA RATON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 161 },
  { name: 'Alpha Lodge', number: '172', city: 'FORT WALTON BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 97 },
  { name: 'Sutherland Lodge', number: '174', city: 'DUNEDIN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 46 },
  { name: 'Jay Lodge', number: '176', city: 'JAY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 40 },
  { name: 'Universal Lodge', number: '178', city: 'TAMPA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 101 },
  { name: 'Hastings Lodge', number: '183', city: 'HASTINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 87 },
  { name: 'A.W. Windhorst Lodge', number: '185', city: 'TAMPA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 115 },
  { name: 'Winter Haven Lodge', number: '186', city: 'WINTER HAVEN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 113 },
  { name: 'William B. Barnett Lodge', number: '187', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 145 },
  { name: 'Nitram Lodge', number: '188', city: 'SAINT PETERSBURG', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 178 },
  { name: 'Groveland Lodge', number: '190', city: 'GROVELAND', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 69 },
  { name: 'Corinthian Lodge', number: '191', city: 'MULBERRY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 47 },
  { name: 'Dunedin Lodge', number: '192', city: 'PALM HARBOR', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 127 },
  { name: 'Archer Lodge', number: '197', city: 'Archer', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 63 },
  { name: 'Zephyr Lodge', number: '198', city: 'ZEPHYRHILLS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 90 },
  { name: 'Bunnell Lodge', number: '200', city: 'BUNNELL', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 84 },
  { name: 'Etna Lodge', number: '202', city: 'WESTVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 11 },
  { name: 'Cottondale Lodge', number: '206', city: 'COTTONDALE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 43 },
  { name: 'Eola Lodge', number: '207', city: 'Orlando', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 189 },
  { name: 'Saint Andrews Lodge', number: '212', city: 'PANAMA CITY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 77 },
  { name: 'Century Lodge', number: '213', city: 'Century', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 36 },
  { name: 'Baldwin Lodge', number: '217', city: 'BALDWIN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 31 },
  { name: 'Haines City Lodge', number: '219', city: 'Lake Alfred', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 62 },
  { name: 'Saint Cloud Lodge', number: '221', city: 'SAINT CLOUD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 90 },
  { name: 'Acme Lodge', number: '222', city: 'PANAMA CITY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 79 },
  { name: 'Glendale Lodge', number: '225', city: 'DEFUNIAK SPRINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 66 },
  { name: 'Clermont Lodge', number: '226', city: 'CLERMONT', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 80 },
  { name: 'Poinciana Lodge', number: '227', city: 'AVON PARK', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 52 },
  { name: 'Frostproof Lodge', number: '229', city: 'FROSTPROOF', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 27 },
  { name: 'Beaver Creek Lodge', number: '230', city: 'BAKER', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 26 },
  { name: 'Sebastian Masonic Lodge', number: '232', city: 'SEBASTIAN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 74 },
  { name: 'Boynton Lodge', number: '236', city: 'BOYNTON BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 130 },
  { name: 'Okeechobee Lodge', number: '237', city: 'OKEECHOBEE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 161 },
  { name: 'Mount Dora Lodge', number: '238', city: 'MOUNT DORA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 101 },
  { name: 'Winter Park Lodge', number: '239', city: 'WINTER PARK', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 253 },
  { name: 'Tampa Lodge', number: '240', city: 'Temple Terrace', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 53 },
  { name: 'Lake Wales Lodge', number: '242', city: 'LAKE WALES', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 87 },
  { name: 'Oviedo Lodge', number: '243', city: 'OVIEDO', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 92 },
  { name: 'Gulf Stream Lodge', number: '245', city: 'Greenacres', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 71 },
  { name: 'Vero Beach Masonic Lodge', number: '250', city: 'VERO BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 104 },
  { name: 'J. F. Swartsel Lodge', number: '251', city: 'LUTZ', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 259 },
  { name: 'Tampa Bay Lodge', number: '252', city: 'PALM HARBOR', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 137 },
  { name: 'West Broward Lodge', number: '253', city: 'PEMBROKE PINES', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 268 },
  { name: 'Luz de America Lodge', number: '255', city: 'MIAMI', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 275 },
  { name: 'Holyrood Lodge', number: '257', city: 'Tampa', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 118 },
  { name: 'Coconut Grove Lodge', number: '258', city: 'SOUTH MIAMI', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 61 },
  { name: 'Coral Gables Lodge', number: '260', city: 'CORAL GABLES', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 117 },
  { name: 'Riverside Lodge', number: '266', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 142 },
  { name: 'Orange Park Lodge', number: '267', city: 'ORANGE PARK', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 227 },
  { name: 'Shamrock Lodge', number: '268', city: 'CROSS CITY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 56 },
  { name: 'Eureka-North Shore Lodge', number: '269', city: 'DANIA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 117 },
  { name: 'Hibiscus Lodge', number: '275', city: 'MIAMI', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 76 },
  { name: 'Bethlehem Lodge', number: '276', city: 'BONIFAY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 112 },
  { name: 'Ensley Lodge', number: '278', city: 'PENSACOLA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 143 },
  { name: 'Sugarland Lodge', number: '281', city: 'CLEWISTON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 38 },
  { name: 'Placid Lodge', number: '282', city: 'LAKE PLACID', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 106 },
  { name: 'Tupelo Lodge', number: '289', city: 'WEWAHITCHKA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 59 },
  { name: 'Gulf Beach Lodge', number: '291', city: 'Madeira Beach', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 164 },
  { name: 'Crawford Lodge', number: '294', city: 'CRAWFORDVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 83 },
  { name: 'Cypress Lodge', number: '295', city: 'NAPLES', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 217 },
  { name: 'Wesconnett Lodge', number: '297', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 103 },
  { name: 'Roe Fulkerson Lodge', number: '299', city: 'HOLLYWOOD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 143 },
  { name: 'Venice Lodge', number: '301', city: 'VENICE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 139 },
  { name: 'Palmwood Lodge', number: '303', city: 'WEST PALM BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 67 },
  { name: 'Robert Butler Lodge', number: '305', city: 'TALLAHASSEE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 104 },
  { name: 'South Miami Lodge', number: '308', city: 'SOUTH MIAMI', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 145 },
  { name: 'Arlington Lodge', number: '309', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 155 },
  { name: 'Okaloosa Lodge', number: '312', city: 'NICEVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 132 },
  { name: 'Harry Jackson Lodge', number: '314', city: 'LYNN HAVEN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 226 },
  { name: 'Village Lodge', number: '315', city: 'MIAMI', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 58 },
  { name: 'Harbor City Lodge', number: '318', city: 'MELBOURNE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 134 },
  { name: 'Cantonment Lodge', number: '322', city: 'CANTONMENT', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 96 },
  { name: 'Marathon Lodge', number: '323', city: 'MARATHON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 108 },
  { name: 'Inglis Lodge', number: '324', city: 'INGLIS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 120 },
  { name: 'Ormond Beach Lodge', number: '326', city: 'ORMOND BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 78 },
  { name: 'Mokanna Lodge', number: '329', city: 'ORLANDO', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 171 },
  { name: 'Temple Terrace Lodge', number: '330', city: 'TEMPLE TERRACE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 96 },
  { name: 'J Dewey Hawkins Lodge', number: '331', city: 'OAKLAND PARK', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 113 },
  { name: 'Bykota Lodge', number: '333', city: 'GREENACRES', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 128 },
  { name: 'Florida Keys Lodge', number: '336', city: 'TAVERNIER', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 64 },
  { name: 'Kathleen Lodge', number: '338', city: 'KATHLEEN', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 167 },
  { name: 'Canaveral Lodge', number: '339', city: 'COCOA BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 74 },
  { name: 'Jupiter Light Lodge', number: '340', city: 'JUPITER', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 189 },
  { name: 'Stafford Caldwell Lodge', number: '342', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 56 },
  { name: 'Mandarin Lodge', number: '343', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 125 },
  { name: 'Phoenix Lodge', number: '346', city: 'SARASOTA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 192 },
  { name: 'Gulf Breeze Lodge', number: '347', city: 'Gulf Breeze', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 79 },
  { name: 'Pace Lodge', number: '349', city: 'PACE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 92 },
  { name: 'R. T. Schafer Lodge', number: '350', city: 'ALACHUA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 80 },
  { name: 'Myrtle Grove Lodge', number: '352', city: 'PENSACOLA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 164 },
  { name: 'Merritt Island Lodge', number: '353', city: 'MERRITT ISLAND', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 146 },
  { name: 'Beach Lodge', number: '354', city: 'INDIALANTIC', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 81 },
  { name: 'Noah Lodge', number: '357', city: 'North Fort Myers', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 71 },
  { name: 'Pythagoras Lodge', number: '358', city: 'PANAMA CITY BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 114 },
  { name: 'Englewood Lodge', number: '360', city: 'ENGLEWOOD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 104 },
  { name: 'J Edwin Larson Lodge', number: '361', city: 'TALLAHASSEE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 103 },
  { name: 'Fort Myers Beach Lodge', number: '362', city: 'FORT MYERS BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 197 },
  { name: 'South Seminole Lodge', number: '364', city: 'CASSELBERRY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 148 },
  { name: 'Garden Lodge', number: '366', city: 'PALM BEACH GARDENS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 92 },
  { name: 'Cape Coral Lodge', number: '367', city: 'FORT MYERS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 109 },
  { name: 'Pine Castle Lodge', number: '368', city: 'PINE CASTLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 131 },
  { name: 'Callaway Lodge', number: '369', city: 'PANAMA CITY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 100 },
  { name: 'Hyde Park Lodge', number: '370', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 76 },
  { name: 'Lantana Lodge', number: '372', city: 'Boynton Beach', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 36 },
  { name: 'LaBelle Lodge', number: '379', city: 'LABELLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 75 },
  { name: 'Omega Lodge', number: '380', city: 'FORT WALTON BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 82 },
  { name: 'Landmark Lodge', number: '383', city: 'ORANGE CITY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 80 },
  { name: 'Gateway Lodge', number: '384', city: 'MIMS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 133 },
  { name: 'Fort King Daylight Lodge', number: '389', city: 'OCALA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 38 },
  { name: 'Travelers Lodge', number: '390', city: 'LAKE ALFRED', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 53 },
  { name: 'Hialeah-Opa Locka Lodge', number: '391', city: 'HIALEAH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 61 },
  { name: 'The Villages Masonic Lodge', number: '394', city: 'LEESBURG', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 127 },
  { name: 'Clyde S. McLaren Lodge', number: '395', city: 'SUNRISE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 80 },
  { name: 'Palm Bay Lodge', number: '397', city: 'MALABAR', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 48 },
  { name: 'Hurricane Lodge', number: '401', city: 'MIAMI SPRINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 38 },
  { name: 'Lewis A. Armistead Lodge', number: '403', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 39 },
  { name: 'Hirams\' Daylight Lodge', number: '407', city: 'CASSELBERRY', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 34 },
  { name: 'Oceanview Lodge', number: '408', city: 'JACKSONVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 105 },
  { name: 'West Coast Lodge', number: '409', city: 'Palmetto', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 68 },
  { name: 'Renacer Lodge', number: '410', city: 'MIAMI SPRINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 124 },
  { name: 'Miami-Dade Hispano-Americana Lodge', number: '411', city: 'SOUTH MIAMI', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 69 },
  { name: 'Liberty Lodge', number: '412', city: 'BRADENTON', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 37 },
  { name: 'Perseverancia Lodge', number: '413', city: 'HIALEAH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 65 },
  { name: 'Fraternidad Lodge', number: '414', city: 'HIALEAH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 74 },
  { name: 'Nuevos Horizontes Lodge', number: '415', city: 'HIALEAH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 41 },
  { name: 'Cornerstone Lodge', number: '416', city: 'Deerfield Beach', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 97 },
  { name: 'John E. Karroum Lodge', number: '417', city: 'HOMESTEAD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 47 },
  { name: 'Nature Coast Masonic Lodge', number: '418', city: 'INVERNESS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 137 },
  { name: 'Paul Revere Lodge', number: '419', city: 'BROOKSVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 93 },
  { name: 'Neptune Beach Lodge', number: '421', city: 'NEPTUNE BEACH', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026', member_count: 223 },
  { name: 'Memorial Lodge', number: '910', city: 'GAINESVILLE', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '912', city: 'OCALA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '913', city: 'Daytona Beach', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '914', city: 'HOMOSASSA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '915', city: 'Tavares', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '916', city: 'SAINT CLOUD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '918', city: 'TARPON SPRINGS', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '920', city: 'TAMPA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '926', city: 'AVENTURA', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '927', city: 'HOMESTEAD', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '934', city: 'Hialeah', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'Memorial Lodge', number: '936', city: 'KEY WEST', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
  { name: 'FLOR Lodge', number: '999', city: 'Jacksonville', state: 'FL', grand_lodge: 'Grand Lodge of Florida', source: 'lodges.glflamason.org — May 2026' },
]