// Demo data — mirrors Supabase DB schema shape (snake_case).
// Used when Demo Mode is ON. Pages swap this in instead of live Supabase queries.

export const DEMO_LODGE_ACACIA    = 'demo-lodge-acacia-123'
export const DEMO_LODGE_GULFCOAST = 'demo-lodge-gulfcoast-441'
export const DEMO_LODGE_SUNCOAST  = 'demo-lodge-suncoast-217'
export const DEMO_PROFILE_ROBERT  = 'demo-profile-robert-ingram'

export const demoLodges = [
  {
    id: DEMO_LODGE_ACACIA,
    name: 'Acacia Lodge',
    number: '123',
    state: 'OK',
    city: 'Tulsa',
    status: 'active',
    tier: 'charter',
    welcome_message: 'Welcome to the Acacia Lodge business directory. All members listed here have been verified by the lodge.',
    created_at: '2023-01-01T00:00:00Z',
  },
  {
    id: DEMO_LODGE_GULFCOAST,
    name: 'Gulf Coast Lodge',
    number: '441',
    state: 'FL',
    city: 'Tampa',
    status: 'active',
    tier: 'charter',
    welcome_message: 'Gulf Coast Lodge #441 — serving Tampa Bay brothers in business.',
    created_at: '2023-01-01T00:00:00Z',
  },
  {
    id: DEMO_LODGE_SUNCOAST,
    name: 'Suncoast Lodge',
    number: '217',
    state: 'FL',
    city: 'Sarasota',
    status: 'active',
    tier: 'standard',
    welcome_message: 'Suncoast Lodge #217 — connecting Sarasota area Masons in commerce.',
    created_at: '2023-01-01T00:00:00Z',
  },
]

export const demoUser = {
  id: DEMO_PROFILE_ROBERT,
  full_name: 'Robert C. Ingram',
  email: 'robert@plumblineplumbing.com',
  lodge_id: DEMO_LODGE_ACACIA,
  lodge_name: 'Acacia Lodge',
  lodge_number: '123',
  trade_category: 'Plumbing',
  city: 'Tulsa',
  state: 'OK',
  lat: 36.1540,
  lng: -95.9928,
  verification_status: 'verified',
  is_lodge_admin: false,
  is_co_admin: false,
  visibility: 'public',
  referral_code: 'RCINGRAM',
  listing_id: 'demo-listing-0004',
  created_at: '2023-01-22T00:00:00Z',
  updated_at: '2023-01-22T00:00:00Z',
}

export const demoListings = [
  {
    id: 'demo-listing-0001',
    profile_id: 'demo-profile-james-thornton',
    business_name: 'Gulf Coast Roofing',
    owner_name: 'James R. Thornton',
    trade_category: 'Roofing',
    lodge_id: DEMO_LODGE_GULFCOAST,
    lodge_name: 'Gulf Coast Lodge',
    lodge_number: '441',
    city: 'Tampa',
    state: 'FL',
    lat: 27.9506, lng: -82.4572,
    description: 'Family-owned roofing company serving the Tampa Bay area for over 20 years. We specialize in residential and light commercial roofing with a reputation for integrity and craftsmanship that reflects our Masonic values.',
    services: ['Roof Replacement', 'Roof Repair', 'Storm Damage Assessment', 'Gutters & Fascia', 'Free Inspections'],
    phone: '(813) 555-0142',
    email: 'james@gulfcoastroofing.com',
    website: 'https://gulfcoastroofing.com',
    google_rating: 4.9,
    google_rating_count: 47,
    travel_radius_miles: 40,
    remote_eligible: false,
    visibility: 'public',
    is_active: true,
    views_count: 284,
    slug: 'gulf-coast-roofing',
    created_at: '2023-03-12T00:00:00Z',
  },
  {
    id: 'demo-listing-0002',
    profile_id: 'demo-profile-marcus-wells',
    business_name: 'Thornton Electric',
    owner_name: 'Marcus D. Wells',
    trade_category: 'Electrical',
    lodge_id: DEMO_LODGE_SUNCOAST,
    lodge_name: 'Suncoast Lodge',
    lodge_number: '217',
    city: 'Sarasota',
    state: 'FL',
    lat: 27.3364, lng: -82.5307,
    description: 'Licensed master electrician with 15 years of experience in residential, commercial, and industrial electrical work. Honest pricing, quality work, and always on time.',
    services: ['Panel Upgrades', 'New Construction Wiring', 'EV Charger Installation', 'Lighting Design', 'Emergency Service'],
    phone: '(941) 555-0288',
    email: 'marcus@thorntonelectric.com',
    website: 'https://thorntonelectric.com',
    google_rating: 4.8,
    google_rating_count: 39,
    travel_radius_miles: 30,
    remote_eligible: false,
    visibility: 'public',
    is_active: true,
    views_count: 196,
    slug: 'thornton-electric',
    created_at: '2023-06-01T00:00:00Z',
  },
  {
    id: 'demo-listing-0003',
    profile_id: 'demo-profile-david-hartley',
    business_name: 'Keystone Legal Group',
    owner_name: 'David A. Hartley',
    trade_category: 'Legal',
    lodge_id: 'demo-lodge-keystone-88',
    lodge_name: 'Keystone Lodge',
    lodge_number: '88',
    city: 'Orlando',
    state: 'FL',
    lat: 28.5383, lng: -81.3792,
    description: 'Full-service law firm focused on business law, estate planning, and real estate transactions. We believe in transparent counsel and building long-term relationships with our clients.',
    services: ['Business Formation', 'Estate Planning', 'Real Estate Closings', 'Contract Review', 'Litigation'],
    phone: '(407) 555-0311',
    email: 'david@keystonelegal.com',
    website: 'https://keystonelegal.com',
    google_rating: 5.0,
    google_rating_count: 28,
    travel_radius_miles: 50,
    remote_eligible: true,
    visibility: 'public',
    is_active: true,
    views_count: 142,
    slug: 'keystone-legal-group',
    created_at: '2022-11-15T00:00:00Z',
  },
  {
    id: 'demo-listing-0004',
    profile_id: DEMO_PROFILE_ROBERT,
    business_name: 'Plumb Line Plumbing',
    owner_name: 'Robert C. Ingram',
    trade_category: 'Plumbing',
    lodge_id: DEMO_LODGE_ACACIA,
    lodge_name: 'Acacia Lodge',
    lodge_number: '123',
    city: 'Tulsa',
    state: 'OK',
    lat: 36.1540, lng: -95.9928,
    description: 'Full-service plumbing for residential and commercial clients throughout the greater Tulsa area. No upsells, no surprises — just honest work at fair prices.',
    services: ['Water Heater Install & Repair', 'Drain Cleaning', 'Leak Detection', 'Repiping', 'Bathroom & Kitchen Remodels'],
    phone: '(918) 555-0477',
    email: 'robert@plumblineplumbing.com',
    website: 'https://plumblineplumbing.com',
    google_rating: 4.7,
    google_rating_count: 62,
    travel_radius_miles: 35,
    remote_eligible: false,
    visibility: 'public',
    is_active: true,
    views_count: 312,
    slug: 'plumb-line-plumbing',
    created_at: '2023-01-22T00:00:00Z',
  },
  {
    id: 'demo-listing-0005',
    profile_id: 'demo-profile-thomas-brewster',
    business_name: 'Level Ground Landscaping',
    owner_name: 'Thomas H. Brewster',
    trade_category: 'Landscaping',
    lodge_id: 'demo-lodge-prairie-56',
    lodge_name: 'Prairie Lodge',
    lodge_number: '56',
    city: 'Oklahoma City',
    state: 'OK',
    lat: 35.4676, lng: -97.5164,
    description: 'Designing and maintaining beautiful outdoor spaces across Oklahoma City and surrounding suburbs. We take pride in our work the same way a craftsman takes pride in his craft.',
    services: ['Lawn Care & Maintenance', 'Landscape Design', 'Irrigation Systems', 'Sod Installation', 'Tree Trimming'],
    phone: '(405) 555-0533',
    email: 'thomas@levelgroundlandscaping.com',
    website: 'https://levelgroundlandscaping.com',
    google_rating: 4.6,
    google_rating_count: 51,
    travel_radius_miles: 40,
    remote_eligible: false,
    visibility: 'public',
    is_active: true,
    views_count: 178,
    slug: 'level-ground-landscaping',
    created_at: '2023-04-08T00:00:00Z',
  },
  {
    id: 'demo-listing-0006',
    profile_id: 'demo-profile-william-mason',
    business_name: 'Square Deal Auto',
    owner_name: 'William F. Mason',
    trade_category: 'Automotive',
    lodge_id: 'demo-lodge-heartland-302',
    lodge_name: 'Heartland Lodge',
    lodge_number: '302',
    city: 'Edmond',
    state: 'OK',
    lat: 35.6528, lng: -97.4781,
    description: 'A square deal means exactly that — fair prices, honest diagnostics, and work done right. Serving Edmond and North OKC for over a decade with ASE-certified technicians.',
    services: ['Oil Changes & Maintenance', 'Engine Diagnostics', 'Brake Service', 'Transmission Repair', 'AC Service'],
    phone: '(405) 555-0622',
    email: 'william@squaredealauto.com',
    website: 'https://squaredealauto.com',
    google_rating: 4.8,
    google_rating_count: 83,
    travel_radius_miles: 25,
    remote_eligible: false,
    visibility: 'public',
    is_active: true,
    views_count: 421,
    slug: 'square-deal-auto',
    created_at: '2022-09-30T00:00:00Z',
  },
  {
    id: 'demo-listing-0007',
    profile_id: 'demo-profile-charles-monroe',
    business_name: 'Craftsman HVAC Services',
    owner_name: 'Charles E. Monroe',
    trade_category: 'HVAC',
    lodge_id: DEMO_LODGE_GULFCOAST,
    lodge_name: 'Gulf Coast Lodge',
    lodge_number: '441',
    city: 'St. Petersburg',
    state: 'FL',
    lat: 27.7676, lng: -82.6403,
    description: 'Keeping Florida comfortable year-round. We install, service, and repair all major HVAC brands and are fully licensed and insured for residential and light commercial work.',
    services: ['AC Installation', 'Heating Systems', 'Preventive Maintenance', 'Duct Cleaning', 'Indoor Air Quality'],
    phone: '(727) 555-0744',
    email: 'charles@craftsmanHVAC.com',
    website: 'https://craftsmanHVAC.com',
    google_rating: 4.9,
    google_rating_count: 55,
    travel_radius_miles: 35,
    remote_eligible: false,
    visibility: 'public',
    is_active: true,
    views_count: 267,
    slug: 'craftsman-hvac-services',
    created_at: '2023-02-14T00:00:00Z',
  },
  {
    id: 'demo-listing-0008',
    profile_id: 'demo-profile-george-whitfield',
    business_name: 'Compass Financial Planning',
    owner_name: 'George L. Whitfield',
    trade_category: 'Financial',
    lodge_id: DEMO_LODGE_SUNCOAST,
    lodge_name: 'Suncoast Lodge',
    lodge_number: '217',
    city: 'Naples',
    state: 'FL',
    lat: 26.1420, lng: -81.7948,
    description: 'Fee-only financial planning firm helping families and small business owners navigate retirement, investments, and estate planning. We work for you — no commissions, no conflicts.',
    services: ['Retirement Planning', 'Investment Management', 'Tax Strategy', 'Estate Planning', 'Small Business Planning'],
    phone: '(239) 555-0855',
    email: 'george@compassfinancial.com',
    website: 'https://compassfinancial.com',
    google_rating: 5.0,
    google_rating_count: 19,
    travel_radius_miles: 50,
    remote_eligible: true,
    visibility: 'public',
    is_active: true,
    views_count: 89,
    slug: 'compass-financial-planning',
    created_at: '2022-08-20T00:00:00Z',
  },
  {
    id: 'demo-listing-0009',
    profile_id: 'demo-profile-henry-price',
    business_name: 'Brotherhood Built Construction',
    owner_name: 'Henry A. Price',
    trade_category: 'General Contractor',
    lodge_id: DEMO_LODGE_ACACIA,
    lodge_name: 'Acacia Lodge',
    lodge_number: '123',
    city: 'Tulsa',
    state: 'OK',
    lat: 36.1540, lng: -95.9928,
    description: 'Full-service general contracting for residential and commercial builds. We manage every phase from foundation to finish with a team that treats your project like it\'s our own.',
    services: ['Custom Home Building', 'Commercial Buildouts', 'Additions & Remodels', 'Project Management', 'Subcontractor Coordination'],
    phone: '(918) 555-0966',
    email: 'henry@brotherhoodbuilt.com',
    website: 'https://brotherhoodbuilt.com',
    google_rating: 4.7,
    google_rating_count: 34,
    travel_radius_miles: 60,
    remote_eligible: false,
    visibility: 'public',
    is_active: true,
    views_count: 156,
    slug: 'brotherhood-built-construction',
    created_at: '2023-05-17T00:00:00Z',
  },
  {
    id: 'demo-listing-0010',
    profile_id: 'demo-profile-samuel-grant',
    business_name: 'True North IT Solutions',
    owner_name: 'Samuel P. Grant',
    trade_category: 'Technology',
    lodge_id: 'demo-lodge-prairie-56',
    lodge_name: 'Prairie Lodge',
    lodge_number: '56',
    city: 'Norman',
    state: 'OK',
    lat: 35.2226, lng: -97.4395,
    description: 'Managed IT services and cybersecurity for small and medium businesses. We\'re your dedicated technology partner — proactive, responsive, and always on your side.',
    services: ['Managed IT Support', 'Cybersecurity', 'Cloud Migration', 'Network Setup', 'Business Continuity Planning'],
    phone: '(405) 555-1044',
    email: 'samuel@truenorthit.com',
    website: 'https://truenorthit.com',
    google_rating: 4.8,
    google_rating_count: 27,
    travel_radius_miles: 40,
    remote_eligible: true,
    visibility: 'public',
    is_active: true,
    views_count: 133,
    slug: 'true-north-it-solutions',
    created_at: '2023-07-03T00:00:00Z',
  },
  {
    id: 'demo-listing-0011',
    profile_id: 'demo-profile-frank-dexter',
    business_name: 'Ashlar Home Inspections',
    owner_name: 'Frank J. Dexter',
    trade_category: 'Home Inspection',
    lodge_id: 'demo-lodge-keystone-88',
    lodge_name: 'Keystone Lodge',
    lodge_number: '88',
    city: 'Jacksonville',
    state: 'FL',
    lat: 30.3322, lng: -81.6557,
    description: 'Certified home inspector with over 2,000 inspections completed. I deliver detailed, honest reports so buyers and sellers know exactly what they\'re working with before closing.',
    services: ['Buyer\'s Inspection', 'Pre-Listing Inspection', 'New Construction Inspection', '4-Point Inspection', 'Wind Mitigation'],
    phone: '(904) 555-1177',
    email: 'frank@ashlarhomeinspections.com',
    website: 'https://ashlarhomeinspections.com',
    google_rating: 4.9,
    google_rating_count: 71,
    travel_radius_miles: 50,
    remote_eligible: false,
    visibility: 'public',
    is_active: true,
    views_count: 344,
    slug: 'ashlar-home-inspections',
    created_at: '2022-12-01T00:00:00Z',
  },
  {
    id: 'demo-listing-0012',
    profile_id: 'demo-profile-arthur-webb',
    business_name: 'Plumb Perfect Painting',
    owner_name: 'Arthur N. Webb',
    trade_category: 'Painting',
    lodge_id: 'demo-lodge-heartland-302',
    lodge_name: 'Heartland Lodge',
    lodge_number: '302',
    city: 'Pensacola',
    state: 'FL',
    lat: 30.4213, lng: -87.2169,
    description: 'Interior and exterior painting with meticulous prep work and clean lines. We treat every home like our own — protecting your space and delivering a finish you\'ll be proud of.',
    services: ['Interior Painting', 'Exterior Painting', 'Cabinet Refinishing', 'Deck & Fence Staining', 'Drywall Repair'],
    phone: '(850) 555-1233',
    email: 'arthur@plumbperfectpainting.com',
    website: 'https://plumbperfectpainting.com',
    google_rating: 4.6,
    google_rating_count: 44,
    travel_radius_miles: 30,
    remote_eligible: false,
    visibility: 'public',
    is_active: true,
    views_count: 211,
    slug: 'plumb-perfect-painting',
    created_at: '2023-08-11T00:00:00Z',
  },
]

export const demoRequests = [
  {
    id: 'demo-req-0001',
    posted_by_name: 'R. Calloway',
    posted_by_email: 'rcalloway@example.com',
    profile_id: 'demo-profile-r-calloway',
    lodge_id: DEMO_LODGE_GULFCOAST,
    lodge_display: 'Gulf Coast Lodge #441',
    category: 'Legal',
    title: 'Looking for a Mason attorney — estate planning, no rush',
    details: 'Need help getting my affairs in order. Looking for a trust and estate attorney who understands the lodge context.',
    city: 'Naples', state: 'FL', lat: 26.1420, lng: -81.7948,
    budget: 'Flexible',
    timeline: 'Within 1 month',
    status: 'active',
    remote_eligible: true,
    is_verified_member: true,
    responses_count: 1,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-04-27T00:00:00Z',
  },
  {
    id: 'demo-req-0002',
    posted_by_name: 'P. Nguyen',
    posted_by_email: 'pnguyen@example.com',
    profile_id: 'demo-profile-p-nguyen',
    lodge_id: 'demo-lodge-prairie-56',
    lodge_display: 'Prairie Lodge #56',
    category: 'Financial',
    title: 'Small business bookkeeping — ongoing monthly engagement',
    details: 'Running a small contracting company. Need someone to handle monthly books, reconciliation, and quarterly estimates.',
    city: 'Oklahoma City', state: 'OK', lat: 35.4676, lng: -97.5164,
    budget: '$200–400/mo',
    timeline: 'Flexible',
    status: 'open',
    remote_eligible: true,
    is_verified_member: true,
    responses_count: 0,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-04-21T00:00:00Z',
  },
  {
    id: 'demo-req-0003',
    posted_by_name: 'D. Harrison',
    posted_by_email: 'dharrison@example.com',
    profile_id: 'demo-profile-d-harrison',
    lodge_id: DEMO_LODGE_SUNCOAST,
    lodge_display: 'Suncoast Lodge #217',
    category: 'Technology',
    title: 'Need IT help — setting up secure network for my law office',
    details: 'Small law office with 4 staff. Need secure file sharing, encrypted email, and proper firewall setup.',
    city: 'Sarasota', state: 'FL', lat: 27.3364, lng: -82.5307,
    budget: '~$800',
    timeline: 'Within 1 week',
    status: 'active',
    remote_eligible: true,
    is_verified_member: true,
    responses_count: 2,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-04-24T00:00:00Z',
  },
  {
    id: 'demo-req-0004',
    posted_by_name: 'H. Price',
    posted_by_email: 'hprice@example.com',
    profile_id: 'demo-profile-henry-price',
    lodge_id: DEMO_LODGE_ACACIA,
    lodge_display: 'Acacia Lodge #123',
    category: 'Plumbing',
    title: 'Pipe leak under kitchen sink — need someone this week',
    details: 'Active drip under the kitchen sink. Shutoff valve not fully stopping it. Need a licensed plumber.',
    city: 'Tulsa', state: 'OK', lat: 36.1540, lng: -95.9928,
    budget: '~$300',
    timeline: 'ASAP',
    status: 'open',
    remote_eligible: false,
    is_verified_member: true,
    responses_count: 0,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-05-26T12:00:00Z',
  },
  {
    id: 'demo-req-0005',
    posted_by_name: 'T. Simmons',
    posted_by_email: 'tsimmons@example.com',
    lodge_display: 'Acacia Lodge #123',
    category: 'Plumbing',
    title: 'Full bathroom remodel — plumbing rough-in needed',
    details: 'Gutting a master bath, moving the toilet 18 inches and adding a double vanity. Need rough-in and finish work.',
    city: 'Tulsa', state: 'OK', lat: 36.1300, lng: -95.9500,
    budget: '~$2,400',
    timeline: 'Within 1 week',
    status: 'active',
    remote_eligible: false,
    is_verified_member: true,
    responses_count: 1,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-05-26T06:00:00Z',
  },
  {
    id: 'demo-req-0006',
    posted_by_name: 'A. Fleming',
    posted_by_email: 'afleming@example.com',
    lodge_display: 'Acacia Lodge #123',
    category: 'Roofing',
    title: 'Roofing inspection before home sale — need report fast',
    details: 'Listing the house next week. Realtor says we need a roof inspection report. Roof is about 12 years old.',
    city: 'Broken Arrow', state: 'OK', lat: 36.0526, lng: -95.7908,
    budget: '~$350',
    timeline: 'ASAP',
    status: 'open',
    remote_eligible: false,
    is_verified_member: true,
    responses_count: 0,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-05-26T10:00:00Z',
  },
  {
    id: 'demo-req-0007',
    posted_by_name: 'L. Graves',
    posted_by_email: 'lgraves@example.com',
    lodge_display: 'Heartland Lodge #302',
    category: 'HVAC',
    title: 'HVAC system replacement — 2,200 sq ft home',
    details: 'Current system is 18 years old and struggling. Looking to replace the whole system before summer.',
    city: 'Edmond', state: 'OK', lat: 35.6528, lng: -97.4781,
    budget: '~$6,000',
    timeline: 'Within 1 month',
    status: 'active',
    remote_eligible: false,
    is_verified_member: true,
    responses_count: 1,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-05-24T00:00:00Z',
  },
  {
    id: 'demo-req-0008',
    posted_by_name: 'W. Mason',
    posted_by_email: 'wmason@example.com',
    lodge_display: 'Heartland Lodge #302',
    category: 'Automotive',
    title: 'Auto repair — transmission issue, daily driver',
    details: 'Slipping between 2nd and 3rd gear. 2019 F-150 with 87k miles. Need an honest shop.',
    city: 'Edmond', state: 'OK', lat: 35.6500, lng: -97.4800,
    budget: 'Market rate',
    timeline: 'ASAP',
    status: 'open',
    remote_eligible: false,
    is_verified_member: false,
    responses_count: 0,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-05-26T08:00:00Z',
  },
  {
    id: 'demo-req-0009',
    posted_by_name: 'C. Monroe',
    posted_by_email: 'cmonroe@example.com',
    lodge_display: 'Heartland Lodge #302',
    category: 'Electrical',
    title: 'Electrical panel upgrade — older home, 200 amp service',
    details: '1960s home with original 100A panel. Getting an EV charger installed and need to upgrade first.',
    city: 'Edmond', state: 'OK', lat: 35.6600, lng: -97.4900,
    budget: '~$2,000',
    timeline: 'Within 1 month',
    status: 'open',
    remote_eligible: false,
    is_verified_member: true,
    responses_count: 0,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-05-25T00:00:00Z',
  },
  {
    id: 'demo-req-0010',
    posted_by_name: 'G. Whitfield',
    posted_by_email: 'gwhitfield@example.com',
    lodge_display: 'Prairie Lodge #56',
    category: 'Plumbing',
    title: 'Plumbing for new build — need rough-in and finish work',
    details: '2,800 sq ft custom home. General contractor has scheduled rough-in to start in 3 weeks.',
    city: 'Oklahoma City', state: 'OK', lat: 35.4676, lng: -97.5164,
    budget: '~$8,500',
    timeline: 'Within 1 month',
    status: 'open',
    remote_eligible: false,
    is_verified_member: true,
    responses_count: 0,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-05-25T12:00:00Z',
  },
  {
    id: 'demo-req-0011',
    posted_by_name: 'T. Brewster',
    posted_by_email: 'tbrewster@example.com',
    lodge_display: 'Prairie Lodge #56',
    category: 'Landscaping',
    title: 'Landscaping overhaul — front and back yard, 0.5 acres',
    details: 'Moving in next month and the yard is a blank slate. Want full design-build: sod, beds, irrigation, trees.',
    city: 'Oklahoma City', state: 'OK', lat: 35.4800, lng: -97.5000,
    budget: '~$4,000',
    timeline: 'Within 1 week',
    status: 'active',
    remote_eligible: false,
    is_verified_member: true,
    responses_count: 2,
    flag_count: 0,
    expires_at: '2026-06-27T00:00:00Z',
    created_at: '2026-05-22T00:00:00Z',
  },
]

export const demoReviews = [
  // Gulf Coast Roofing (demo-listing-0001)
  { id: 'demo-rev-001', listing_id: 'demo-listing-0001', reviewer_id: 'demo-profile-henry-price', reviewer_name: 'H. Price', rating: 5, body: 'James did my whole roof after the storm and was incredible to work with. Fair price, on time, and zero drama.', created_at: '2025-11-01T00:00:00Z' },
  { id: 'demo-rev-002', listing_id: 'demo-listing-0001', reviewer_id: 'demo-profile-d-harrison', reviewer_name: 'D. Harrison', rating: 5, body: 'Recommended by my lodge. He inspected, quoted, and completed the job in under 2 weeks. Top tier.', created_at: '2025-09-14T00:00:00Z' },
  { id: 'demo-rev-003', listing_id: 'demo-listing-0001', reviewer_id: 'demo-profile-a-fleming', reviewer_name: 'A. Fleming', rating: 5, body: 'Honest inspection report that saved me from buying a house with a bad roof. Worth every penny.', created_at: '2025-07-22T00:00:00Z' },
  // Plumb Line Plumbing (demo-listing-0004)
  { id: 'demo-rev-004', listing_id: 'demo-listing-0004', reviewer_id: 'demo-profile-henry-price', reviewer_name: 'H. Price', rating: 5, body: 'Robert fixed a slab leak that two other plumbers couldn\'t find. Methodical, clean, fair.', created_at: '2025-12-03T00:00:00Z' },
  { id: 'demo-rev-005', listing_id: 'demo-listing-0004', reviewer_id: 'demo-profile-thomas-brewster', reviewer_name: 'T. Brewster', rating: 5, body: 'Did the plumbing for my whole addition. Showed up every day, no excuses, and the inspection passed first try.', created_at: '2025-10-18T00:00:00Z' },
  { id: 'demo-rev-006', listing_id: 'demo-listing-0004', reviewer_id: 'demo-profile-william-mason', reviewer_name: 'W. Mason', rating: 4, body: 'Solid plumber, fair rates. Takes his time which means quality work. Scheduling took a few days.', created_at: '2025-08-05T00:00:00Z' },
  // Thornton Electric (demo-listing-0002)
  { id: 'demo-rev-007', listing_id: 'demo-listing-0002', reviewer_id: DEMO_PROFILE_ROBERT, reviewer_name: 'R. Ingram', rating: 5, body: 'Marcus upgraded my panel and installed 2 EV chargers. Explained everything clearly, no surprises on the bill.', created_at: '2025-11-29T00:00:00Z' },
  { id: 'demo-rev-008', listing_id: 'demo-listing-0002', reviewer_id: 'demo-profile-charles-monroe', reviewer_name: 'C. Monroe', rating: 5, body: 'He wired a new workshop for me. Showed up early every day and left the place cleaner than he found it.', created_at: '2025-10-02T00:00:00Z' },
  { id: 'demo-rev-009', listing_id: 'demo-listing-0002', reviewer_id: 'demo-profile-samuel-grant', reviewer_name: 'S. Grant', rating: 5, body: 'Did the electrical for our office buildout. On budget, on time, all code compliant. Will use again.', created_at: '2025-08-17T00:00:00Z' },
]

export const demoData = {
  user: demoUser,
  lodges: demoLodges,
  listings: demoListings,
  requests: demoRequests,
  reviews: demoReviews,
}
