import { TradeCategory } from "@/lib/types";

export type RequestStatus = "open" | "active" | "filled";
export type RequestTimeline = "ASAP" | "Within 1 week" | "Within 2 weeks" | "Within 1 month" | "Flexible";

export interface ServiceRequest {
  id: number;
  title: string;
  category: TradeCategory;
  name: string;
  lodge: string;
  city: string;
  state: string;
  lat: number;
  lng: number;
  budget: string;
  timeline: RequestTimeline;
  details?: string;
  responses: number;
  postedHoursAgo: number;
  status: RequestStatus;
  remoteEligible: boolean;
  verifiedMember: boolean;
}

export const requests: ServiceRequest[] = [
  {
    id: 1,
    title: "Looking for a Mason attorney — estate planning, no rush",
    category: "Legal",
    name: "R. Calloway",
    lodge: "Gulf Coast Lodge #441",
    city: "Naples",
    state: "FL",
    lat: 26.1420,
    lng: -81.7948,
    budget: "Flexible",
    timeline: "Within 1 month",
    responses: 1,
    postedHoursAgo: 96,
    status: "active",
    remoteEligible: true,
    verifiedMember: true,
  },
  {
    id: 2,
    title: "Small business bookkeeping — ongoing monthly engagement",
    category: "Financial",
    name: "P. Nguyen",
    lodge: "Prairie Lodge #56",
    city: "Oklahoma City",
    state: "OK",
    lat: 35.4676,
    lng: -97.5164,
    budget: "$200–400/mo",
    timeline: "Flexible",
    responses: 0,
    postedHoursAgo: 144,
    status: "open",
    remoteEligible: true,
    verifiedMember: true,
  },
  {
    id: 3,
    title: "Need IT help — setting up secure network for my law office",
    category: "Technology",
    name: "D. Harrison",
    lodge: "Suncoast Lodge #217",
    city: "Sarasota",
    state: "FL",
    lat: 27.3364,
    lng: -82.5307,
    budget: "~$800",
    timeline: "Within 2 weeks",
    responses: 2,
    postedHoursAgo: 72,
    status: "active",
    remoteEligible: true,
    verifiedMember: true,
  },
  {
    id: 4,
    title: "Pipe leak under kitchen sink — need someone this week",
    category: "Plumbing",
    name: "H. Price",
    lodge: "Acacia Lodge #123",
    city: "Tulsa",
    state: "OK",
    lat: 36.1540,
    lng: -95.9928,
    budget: "~$300",
    timeline: "ASAP",
    responses: 0,
    postedHoursAgo: 12,
    status: "open",
    remoteEligible: false,
    verifiedMember: true,
  },
  {
    id: 5,
    title: "Full bathroom remodel — plumbing rough-in needed",
    category: "Plumbing",
    name: "T. Simmons",
    lodge: "Acacia Lodge #123",
    city: "Tulsa",
    state: "OK",
    lat: 36.1300,
    lng: -95.9500,
    budget: "~$2,400",
    timeline: "Within 2 weeks",
    responses: 1,
    postedHoursAgo: 30,
    status: "active",
    remoteEligible: false,
    verifiedMember: true,
  },
  {
    id: 6,
    title: "Roofing inspection before home sale — need report fast",
    category: "Roofing",
    name: "A. Fleming",
    lodge: "Acacia Lodge #123",
    city: "Broken Arrow",
    state: "OK",
    lat: 36.0526,
    lng: -95.7908,
    budget: "~$350",
    timeline: "ASAP",
    responses: 0,
    postedHoursAgo: 18,
    status: "open",
    remoteEligible: false,
    verifiedMember: true,
  },
  {
    id: 7,
    title: "HVAC system replacement — 2,200 sq ft home",
    category: "HVAC",
    name: "L. Graves",
    lodge: "Heartland Lodge #302",
    city: "Edmond",
    state: "OK",
    lat: 35.6528,
    lng: -97.4781,
    budget: "~$6,000",
    timeline: "Within 1 month",
    responses: 1,
    postedHoursAgo: 72,
    status: "active",
    remoteEligible: false,
    verifiedMember: true,
  },
  {
    id: 8,
    title: "Auto repair — transmission issue, daily driver",
    category: "Automotive",
    name: "W. Mason",
    lodge: "Heartland Lodge #302",
    city: "Edmond",
    state: "OK",
    lat: 35.6500,
    lng: -97.4800,
    budget: "Market rate",
    timeline: "ASAP",
    responses: 0,
    postedHoursAgo: 14,
    status: "open",
    remoteEligible: false,
    verifiedMember: false,
  },
  {
    id: 9,
    title: "Electrical panel upgrade — older home, 200 amp service",
    category: "Electrical",
    name: "C. Monroe",
    lodge: "Heartland Lodge #302",
    city: "Edmond",
    state: "OK",
    lat: 35.6600,
    lng: -97.4900,
    budget: "~$2,000",
    timeline: "Within 1 month",
    responses: 0,
    postedHoursAgo: 48,
    status: "open",
    remoteEligible: false,
    verifiedMember: true,
  },
  {
    id: 10,
    title: "Plumbing for new build — need rough-in and finish work",
    category: "Plumbing",
    name: "G. Whitfield",
    lodge: "Prairie Lodge #56",
    city: "Oklahoma City",
    state: "OK",
    lat: 35.4676,
    lng: -97.5164,
    budget: "~$8,500",
    timeline: "Within 1 month",
    responses: 0,
    postedHoursAgo: 60,
    status: "open",
    remoteEligible: false,
    verifiedMember: true,
  },
  {
    id: 11,
    title: "Landscaping overhaul — front and back yard, 0.5 acres",
    category: "Landscaping",
    name: "T. Brewster",
    lodge: "Prairie Lodge #56",
    city: "Oklahoma City",
    state: "OK",
    lat: 35.4800,
    lng: -97.5000,
    budget: "~$4,000",
    timeline: "Within 2 weeks",
    responses: 2,
    postedHoursAgo: 120,
    status: "active",
    remoteEligible: false,
    verifiedMember: true,
  },
];

// Backward-compatible alias used by admin/gaps
export const serviceRequests = requests;
